-- Historial inmutable de importes generados por reservas completas.
-- Es independiente de pagos/reembolsos y puede aplicarse repetidamente.
CREATE TABLE IF NOT EXISTS consumos_reserva (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva integer NOT NULL UNIQUE REFERENCES reservas(id),
    id_trato integer NOT NULL REFERENCES trato_empresa_garage(id),
    id_sede integer NOT NULL REFERENCES sedes(id),
    id_empresa integer NOT NULL REFERENCES empresas(id),
    id_garage integer NOT NULL REFERENCES garages(id),
    tipo_vehiculo tipo_vehiculo_enum NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    minutos_facturados integer NOT NULL CHECK (minutos_facturados >= 0),
    tarifa_hora_aplicada numeric(12,2) NOT NULL CHECK (tarifa_hora_aplicada >= 0),
    importe_generado numeric(12,2) NOT NULL CHECK (importe_generado >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_consumos_reserva_empresa_periodo
    ON consumos_reserva (id_empresa, fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_consumos_reserva_sede_periodo
    ON consumos_reserva (id_sede, fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_consumos_reserva_garage_periodo
    ON consumos_reserva (id_garage, fecha_inicio);

-- No se hace un INSERT histórico automático: usar precios actuales para reservas
-- antiguas alteraría la historia. `npm run check:consumos` informa las reservas
-- completas sin snapshot para que se resuelvan con una tarifa verificable.
